export const initialState = [
  {
    name: "Qatar",
    index: 0,
    group: "A",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Ecuador",
    index: 1,
    group: "A",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Senegal",
    index: 2,
    group: "A",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Netherlands",
    index: 3,
    group: "A",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "England",
    index: 0,
    group: "B",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Iran",
    index: 1,
    group: "B",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "USA",
    index: 2,
    group: "B",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "To de decided 1",
    index: 3,
    group: "B",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Argentina",
    index: 0,
    group: "C",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Saudi Arabia",
    index: 1,
    group: "C",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Mexico",
    index: 2,
    group: "C",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Poland",
    index: 3,
    group: "C",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "France",
    index: 0,
    group: "D",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "To be decided 2",
    index: 1,
    group: "D",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Denmark",
    index: 2,
    group: "D",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Tunisia",
    index: 3,
    group: "D",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Spain",
    index: 0,
    group: "E",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "To be decided 3",
    index: 1,
    group: "E",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Germany",
    index: 2,
    group: "E",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Japan",
    index: 3,
    group: "E",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Belgium",
    index: 0,
    group: "F",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Canada",
    index: 1,
    group: "F",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Marroco",
    index: 2,
    group: "F",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Croatia",
    index: 3,
    group: "F",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Brazil",
    index: 0,
    group: "G",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Serbia",
    index: 1,
    group: "G",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Switzerland",
    index: 2,
    group: "G",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Cameroon",
    index: 3,
    group: "G",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Portugal",
    index: 0,
    group: "H",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Ghana",
    index: 1,
    group: "H",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Uruguay",
    index: 2,
    group: "H",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "South Korea",
    index: 3,
    group: "H",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
];
