export const initialState = [
  {
    name: "Qatar",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/320px-Flag_of_Qatar.svg.png",
    index: 0,
    group: "A",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Ecuador",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/320px-Flag_of_Ecuador.svg.png",
    index: 1,
    group: "A",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Senegal",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/320px-Flag_of_Senegal.svg.png",
    index: 2,
    group: "A",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Netherlands",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/320px-Flag_of_the_Netherlands.svg.png",
    index: 3,
    group: "A",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "England",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Flag_of_England.svg/320px-Flag_of_England.svg.png",
    index: 0,
    group: "B",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Iran",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/320px-Flag_of_Iran.svg.png",
    index: 1,
    group: "B",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "USA",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/320px-Flag_of_the_United_States.svg.png",
    index: 2,
    group: "B",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "To de decided 1",
    index: 3,
    group: "B",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Argentina",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/320px-Flag_of_Argentina.svg.png",
    index: 0,
    group: "C",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Saudi Arabia",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/320px-Flag_of_Saudi_Arabia.svg.png",
    index: 1,
    group: "C",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Mexico",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/320px-Flag_of_Mexico.svg.png",
    index: 2,
    group: "C",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Poland",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/320px-Flag_of_Poland.svg.png",
    index: 3,
    group: "C",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "France",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/320px-Flag_of_France.svg.png",
    index: 0,
    group: "D",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "To be decided 2",
    index: 1,
    group: "D",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Denmark",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/318px-Flag_of_Denmark.svg.png",
    index: 2,
    group: "D",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Tunisia",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/320px-Flag_of_Tunisia.svg.png",
    index: 3,
    group: "D",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Spain",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/320px-Flag_of_Spain.svg.png",
    index: 0,
    group: "E",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "To be decided 3",
    index: 1,
    group: "E",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Germany",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/320px-Flag_of_Germany.svg.png",
    index: 2,
    group: "E",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Japan",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/320px-Flag_of_Japan.svg.png",
    index: 3,
    group: "E",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Belgium",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/277px-Flag_of_Belgium.svg.png",
    index: 0,
    group: "F",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Canada",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/320px-Flag_of_Canada.svg.png",
    index: 1,
    group: "F",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Marroco",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/320px-Flag_of_Morocco.svg.png",
    index: 2,
    group: "F",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Croatia",
    flag: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg",
    index: 3,
    group: "F",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Brazil",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/320px-Flag_of_Brazil.svg.png",
    index: 0,
    group: "G",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Serbia",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/320px-Flag_of_Serbia.svg.png",
    index: 1,
    group: "G",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Switzerland",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/240px-Flag_of_Switzerland.svg.png",
    index: 2,
    group: "G",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Cameroon",
    index: 3,
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/320px-Flag_of_Cameroon.svg.png",
    group: "G",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Portugal",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/320px-Flag_of_Portugal.svg.png",
    index: 0,
    group: "H",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Ghana",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/320px-Flag_of_Ghana.svg.png",
    index: 1,
    group: "H",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "Uruguay",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/320px-Flag_of_Uruguay.svg.png",
    index: 2,
    group: "H",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
  {
    name: "South Korea",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/320px-Flag_of_South_Korea.svg.png",
    index: 3,
    group: "H",
    oitavas: false,
    quartas: false,
    semi: false,
    final: false,
  },
];
