import Head from "next/head";
import Groups from "../components/Groups/Groups";
import Finals from "../components/Finals/Finals";
import KnockOut from "../components/Finals/KnockOut";
import { Header } from "../components/Header";
import { Flex } from "@chakra-ui/react";
import { CupState } from "../context/Context";
import { useEffect } from "react";

export default function Home() {
  const { state, dispatch } = CupState();
  useEffect(() => {
    if (localStorage.getItem("state"))
      dispatch({
        type: "LOADING",
        value: JSON.parse(localStorage.getItem("state")),
      });
  }, []);

  useEffect(() => {
    localStorage.setItem("state", JSON.stringify(state));
  }, [state]);

  return (
    <div>
      <Head>
        <title>World Cup Simulator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>
        <Header />
      </Flex>
      {state.ui === "groups" && <Groups />}
      {/* {state.ui === "finals" && <Finals />} */}
      {state.ui === "finals" && <KnockOut />}
    </div>
  );
}
