import Head from "next/head";
import Groups from "../components/Groups/Groups";
import Finals from "../components/Finals/Finals";
import { useState } from "react";
import { Button, Flex } from "@chakra-ui/react";

export default function Home() {
  const [ui, setUI] = useState("group");
  const uiHandler = (key) => setUI(key);
  return (
    <div>
      <Head>
        <title>World Cup Simulator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>
        <Button onClick={() => uiHandler("group")}>Group Stage</Button>
        <Button onClick={() => uiHandler("finals")}>Play Offs</Button>
      </Flex>
      {ui === "group" && <Groups />}
      {ui === "finals" && <Finals />}
    </div>
  );
}
